# version: '3.8'

services:
  spotify-clone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-clone-app
    ports:
      - "3000:80"   # Host 3000 â†’ container 80
    restart: unless-stopped
    networks:
      - spotify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  spotify-network:
    driver: bridge
