services:
  spotify-clone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-clone-app
    ports:
      - "3000:80"
    volumes:
      - ./music:/usr/share/nginx/html/music   # map local music folder
    restart: unless-stopped
    networks:
      - spotify-network
